```{r kmfunc, cache=cacheon}

kmfunc <- function(time, event, eventmod = NULL, eventname, ymax = 1, rep = FALSE) {
  fits <- survfit(formula(paste0("Surv(", time, ",", event, "== 'Yes') ~ sos_ddr_sglt2")),
    data = rsdata
  )
  fitsm <- survfit(formula(paste0("Surv(", time, ",", event, "== 'Yes') ~ sos_ddr_sglt2")),
    data = matchrsdata
  )

  if (!rep) {
    # cox model
    mod <- coxph(formula(paste0("Surv(", time, ",", event, "=='Yes') ~ sos_ddr_sglt2")),
      data = rsdata
    )
    smod <- summary(mod)
    hrprintcrude <- c("ref", paste0(
      fn(smod$conf.int[1, 1], dig = 2),
      " (", fn(smod$conf.int[1, 3], dig = 2),
      "-", fn(smod$conf.int[1, 4], dig = 2), "), ",
      fn(smod$coef[1, 5], dig = 3, p = TRUE)
    ))
    # matched
    mod <- coxph(formula(paste0("Surv(", time, ",", event, "=='Yes') ~ sos_ddr_sglt2 + frailty.gaussian(par)")),
      data = matchrsdata
    )
    se <- sqrt(vcov(mod)[1])

    hrprintadj <- c("ref", paste0(
      fn(exp(mod$coefficients[1]), dig = 2),
      " (", fn(exp(mod$coefficients[1] - global_z05 * se), dig = 2),
      "-", fn(exp(mod$coefficients[1] + global_z05 * se), dig = 2), "), ",
      fn((1 - pnorm(abs(mod$coeff[1] / se))) * 2, dig = 3, p = TRUE)
    ))
  }
  if (rep) {
    mod <- summary(glm.nb(formula(paste0(eventmod, " ~ sos_ddr_sglt2 + offset(log(sos_outtime_death))")),
      data = rsdata %>% filter(sos_outtime_death > 0)
    ))

    hrprintcrude <- c("ref", paste0(
      fn(exp(mod$coefficients[2, 1]), dig = 2),
      " (", fn(exp(mod$coefficients[2, 1] - global_z05 * mod$coefficients[2, 2]), dig = 2),
      "-", fn(exp(mod$coefficients[2, 1] + global_z05 * mod$coefficients[2, 2]), dig = 2), "), ",
      fn(mod$coefficients[2, 4], dig = 3, p = TRUE)
    ))

    # matched
    mod <- summary(lme4::glmer.nb(formula(paste0(eventmod, " ~
                                                     sos_ddr_sglt2 + offset(log(sos_outtime_death)) + (1 | par)")),
      data = matchrsdata
    ))
    se <- sqrt(vcov(mod)[1])

    hrprintadj <- c("ref", paste0(
      fn(exp(mod$coefficients[2, 1]), dig = 2),
      " (", fn(exp(mod$coefficients[2, 1] - global_z05 * mod$coefficients[2, 2]), dig = 2),
      "-", fn(exp(mod$coefficients[2, 1] + global_z05 * mod$coefficients[2, 2]), dig = 2), "), ",
      fn(mod$coefficients[2, 4], dig = 3, p = TRUE)
    ))

    fitsr <- mcf(formula(paste0("Recur(sos_outtime, lopnr, ", event, " == 1) ~ sos_ddr_sglt2")),
      data = rsdata_rec
    )
    fitsrm <- mcf(formula(paste0("Recur(sos_outtime, lopnr, ", event, " == 1) ~ sos_ddr_sglt2")),
      data = matchrsdata_rec
    )
  }

  # c(bottom, left, top, right)
  cexmy <- 1.2
  par(mar = c(8.5, 11, 1, 1.5) + 0.1)

  if (!rep) {
    plots <- plot(fits,
      fun = "event",
      ylab = paste0(eventname, " (%)"),
      yscale = 100,
      xscale = 30.5,
      col = global_cols[c(2, 4)],
      mark.time = FALSE,
      bty = "n",
      xlim = c(0, 12 * 30),
      ylim = c(0, ymax + 0.05),
      xlab = "Follow-up (months)",
      cex.lab = cexmy,
      axes = F,
      lwd = 2,
      lty = 1,
      xaxs = "i", yaxs = "i"
    )
    lines(fitsm,
      fun = "event",
      xscale = 365,
      xscale = 30.5,
      col = global_cols[c(2, 4)],
      mark.time = FALSE,
      conf.int = FALSE,
      lwd = 2,
      lty = 3,
      xaxs = "i", yaxs = "i"
    )

    axis(2, seq(0, ymax + 0.05, 0.05), c(seq(0, ymax * 100, 5), 100), las = 2, cex.axis = cexmy)
    plotrix::axis.break(2, ymax + 0.025, style = "slash")
  }

  if (rep) {
    plot(fitsr@MCF$time[fitsr@MCF["sos_ddr_sglt2"] == "No"],
      fitsr@MCF$MCF[fitsr@MCF["sos_ddr_sglt2"] == "No"],
      type = "l",
      ylab = paste0("Mean cumulative ", eventname, " (per 100 patients)"),
      col = global_cols[2],
      xlim = c(0, 12 * 30),
      ylim = c(0, ymax + 0.05),
      xlab = "Follow-up (months)",
      cex.lab = cexmy,
      axes = F,
      lwd = 2,
      lty = 1,
      xaxs = "i", yaxs = "i"
    )
    lines(fitsr@MCF$time[fitsr@MCF["sos_ddr_sglt2"] == "Yes"],
      fitsr@MCF$MCF[fitsr@MCF["sos_ddr_sglt2"] == "Yes"],
      col = global_cols[4],
      lwd = 2,
      lty = 1
    )
    lines(fitsrm@MCF$time[fitsrm@MCF["sos_ddr_sglt2"] == "No"],
      fitsrm@MCF$MCF[fitsrm@MCF["sos_ddr_sglt2"] == "No"],
      col = global_cols[2],
      lwd = 2,
      lty = 3
    )
    lines(fitsrm@MCF$time[fitsrm@MCF["sos_ddr_sglt2"] == "Yes"],
      fitsrm@MCF$MCF[fitsrm@MCF["sos_ddr_sglt2"] == "Yes"],
      col = global_cols[4],
      lwd = 2,
      lty = 3
    )

    axis(2, seq(0, ymax, 0.5), seq(0, ymax * 100, 50), las = 2, cex.axis = cexmy)
  }

  axis(1, at = seq(0, 12, 2) * 30, seq(0, 12, 2), cex.axis = cexmy)

  levs <- c("No SGLT2i (crude)", "SGLT2i (crude)", "No SGLT2i (adjusted)", "SGLT2i (adjusted)")

  legend(
    x = 0.5, y = ymax + 0.05, bty = "n", c("", levs),
    col = c("white", global_cols[c(2, 4, 2, 4)]), cex = cexmy, lwd = 2, lty = c(1, 1, 1, 3, 3),
    text.col = c("white", global_cols[c(2, 4, 2, 4)])
  )
  legend(x = 9 * 30, y = ymax + 0.05, c("HR (95% CI), p-value", hrprintcrude, hrprintadj), 
         cex = cexmy, adj = 0.5, bty = "n")

  mtext("No. at risk", side = 1, line = 3.7, at = -143, adj = 0, cex = cexmy, font = 2)
  mtext(levs[1], side = 1, line = 4.7, at = -143, adj = 0, cex = cexmy, col = global_cols[2])
  mtext(levs[2], side = 1, line = 5.7, at = -143, adj = 0, cex = cexmy, col = global_cols[4])
  mtext(levs[3], side = 1, line = 6.7, at = -143, adj = 0, cex = cexmy, col = global_cols[2])
  mtext(levs[4], side = 1, line = 7.7, at = -143, adj = 0, cex = cexmy, col = global_cols[4])

  nrisk <- summary(fits, seq(0, 12, 2) * 30, extend = T)
  nriskadj <- summary(fitsm, seq(0, 12, 2) * 30, extend = T)

  axis(1,
    at = seq(0, 12, 2) * 30, labels = nrisk$n.risk[nrisk$strata == "sos_ddr_sglt2=No"],
    line = 3.7, tick = FALSE, cex.axis = cexmy
  )
  axis(1,
    at = seq(0, 12, 2) * 30, labels = nrisk$n.risk[nrisk$strata == "sos_ddr_sglt2=Yes"],
    line = 4.7, tick = FALSE, cex.axis = cexmy
  )
  axis(1,
    at = seq(0, 12, 2) * 30, labels = nriskadj$n.risk[nrisk$strata == "sos_ddr_sglt2=No"],
    line = 5.7, tick = FALSE, cex.axis = cexmy
  )
  axis(1,
    at = seq(0, 12, 2) * 30, labels = nriskadj$n.risk[nrisk$strata == "sos_ddr_sglt2=Yes"],
    line = 6.7, tick = FALSE, cex.axis = cexmy
  )
}
```

```{r kmcvdeathhfh, fig.cap="CVD/First HF hospitalization", cache=cacheon, dependson="kmfunc", fig.width=8, fig.height=7}
kmfunc(
  time = "sos_outtime_hosphf",
  event = "sos_out_deathcvhosphf",
  eventname = "CVD/First HFH",
  ymax = 0.4
)
```

```{r kmacvdeath, fig.cap="CVD", cache=cacheon, dependson="kmfunc", fig.width=8, fig.height=7}
kmfunc(
  time = "sos_outtime_death",
  event = "sos_out_deathcv",
  eventname = "CVD",
  ymax = 0.1
)
```

```{r kmhfh, fig.cap="First HF hospitalization", cache=cacheon, dependson="kmfunc", fig.width=8, fig.height=7}
kmfunc(
  time = "sos_outtime_hosphf",
  event = "sos_out_hosphf",
  eventname = "CVD/First HFH",
  ymax = 0.4
)
```

```{r kmtothfh, fig.cap="Total HF hospitalization", cache=cacheon, dependson="kmfunc", fig.width=8, fig.height=7}
kmfunc(
  event = "sos_out_hosphf",
  eventmod = "sos_out_counthosphf",
  time = "sos_outtime_death",
  eventname = "HFH",
  ymax = 1,
  rep = T
)
```

```{r kmdeath, fig.cap="All-cause mortality", cache=cacheon, dependson="kmfunc", fig.width=8, fig.height=7}
kmfunc(
  time = "sos_outtime_death",
  event = "sos_out_death",
  eventname = "All-cause mortality",
  ymax = 0.2
)
```

```{r kmrenalhosp, fig.cap="First kidney hospitalization", cache=cacheon, dependson="kmfunc", fig.width=8, fig.height=7}
kmfunc(
  time = "sos_outtime_hosprenal",
  event = "sos_out_hosprenal",
  eventname = "First kidney hospitalization",
  ymax = 0.1
)
```
