```{r ortabfunc, cache=cacheon}

predfunc <- function(sglt2var, impdata = imprsdata) {

  # mult
  ormod <- with(impdata, glm(formula(paste0(sglt2var, "== 'Yes' ~ ", paste(modvars, collapse = " + "))),
    family = binomial(link = "logit")
  ))

  sormod <- summary(pool(ormod))
  nval <- length(sormod$term)

  preds <- bind_cols(
    Variable = as.character(sormod$term[2:nval]),
    logor = sormod$estimate[2:nval],
    lci = sormod$estimate[2:nval] - global_z05 * sormod$std.error[2:nval],
    uci = sormod$estimate[2:nval] + global_z05 * sormod$std.error[2:nval],
    p = fn(sormod$p.value[2:nval], dig = 3, p = TRUE)
  ) %>%
    mutate(orci = paste0(
      fn(exp(logor), 2),
      " (", fn(exp(lci), 2), "-",
      fn(exp(uci), 2), ")"
    )) %>%
    select(Variable, logor, lci, uci, orci, p) %>%
    mutate(
      Variable = str_replace(Variable, fixed("Yes"), "")
    )

  # crude
  for (i in seq_along(modvars)) {
    ormoduni <- with(impdata, glm(formula(paste0(sglt2var, "== 'Yes' ~ ", modvars[i])),
      family = binomial(link = "logit")
    ))

    sormoduni <- summary(pool(ormoduni))

    nval <- length(sormoduni$term)

    predsunitmp <- bind_cols(
      Variable = as.character(sormoduni$term[2:nval]),
      logor = sormoduni$estimate[2:nval],
      lci = sormoduni$estimate[2:nval] - global_z05 * sormoduni$std.error[2:nval],
      uci = sormoduni$estimate[2:nval] + global_z05 * sormoduni$std.error[2:nval],
      p = fn(sormoduni$p.value[2:nval], dig = 3, p = TRUE)
    ) %>%
      mutate(orci = paste0(
        fn(exp(logor), 2),
        " (", fn(exp(lci), 2), "-",
        fn(exp(uci), 2), ")"
      )) %>%
      select(Variable, logor, lci, uci, orci, p) %>%
      mutate(
        Variable = str_replace(Variable, fixed("Yes"), "")
      )

    if (i == 1) {
      predsuni <<- predsunitmp
    } else {
      predsuni <<- bind_rows(predsuni, predsunitmp)
    }
  }

  predall <- full_join(predsuni,
    preds,
    by = "Variable"
  )

  predall <- predall %>%
    mutate(across(everything(), str_replace_all, fixed("Yes"), "")) %>%
    mutate(Variable = str_replace_all(Variable, "shf_sos_com_", "sos_com_"))

  predall <- left_join(predall,
    meta_variables %>%
      select(variable, label),
    by = c("Variable" = "variable")
  ) %>%
    mutate(
      Variable = coalesce(label, Variable)
    ) %>%
    mutate(Variable = case_when(
      Variable == "shf_sexMale" ~ "Male vs female",
      Variable == "shf_age_cat>=75" ~ "Age (years) >=75 vs < 75",
      Variable == "shf_sos_prevhfhPrevious HFH <1 year" ~ "Previous HFH <1 year",
      Variable == "shf_followuplocation_catHospital" ~ "Follow-up hospital vs primary care/other",
      Variable == "shf_ef<30" ~ "EF (%) <30 vs 30-39",
      Variable == "shf_durationhf>6mo" ~ "Duration HF (mo) >=6 vs <6",
      Variable == "shf_nyha_catIII-IV" ~ "NYHA class III-IV vs I-II",
      Variable == "shf_bmi_cat>=30" ~ "BMI (kg/m2) >=30 vs <30",
      Variable == "shf_map_cat>90" ~ "MAP >90 vs <=90",
      Variable == "shf_heartrate_cat>70" ~ "Heart rate (beats/min) >70 vs <=70",
      Variable == "shf_gfrckdepi_cat<60" ~ "eGFR (mL/min/1.73 m²) <60 vs >=60",
      Variable == "shf_potassium_cathyperkalemia" ~ "Hyperkalemia vs normakalemia",
      Variable == "shf_potassium_cathypokalemia" ~ "Hypokalemia vs normakalemia",
      Variable == "shf_ntprobnp_cat>=median" ~ "NT-proBNP (pg/ml) >=median vs <median",
      Variable == "shf_device_catCRT/ICD" ~ "CRT/ICD",
      Variable == "scb_famtypeLiving alone" ~ "Living alone vs cohabitating",
      Variable == "scb_educationSecondary school" ~ "Secondary vs compulsory school",
      Variable == "scb_educationUniversity" ~ "University vs compulsory school",
      Variable == "scb_dispincome_cat>=median" ~ "Income >=median vs <median",
      Variable == "shf_indexyearmonth_num" ~ "Index year:month",
      TRUE ~ Variable
    ))

  predallprint <- predall %>%
    select(Variable, "orci.x", "p.x", "orci.y", "p.y")

  predout <- list(predallprint = predallprint, predall = predall)
  return(predout)
}
```

```{r orforestfunc, cache=cacheon}
plotforest <- function(forestdata) {
  cextext <- 0.8

  forestdata <- forestdata %>%
    mutate(
      Variable = str_replace_all(Variable, ">=", "\u2265"),
      Variable = str_replace_all(Variable, "<=", "\u2264")
    ) %>%
    mutate(
      order = n():1 - 1,
      pnum = as.numeric(p),
      cols = if_else(is.na(p) | p < 0.05, global_cols[1], global_cols[5])
    )

  minmy <- round(exp(min(forestdata$lci, na.rm = T)), 2)
  maxmy <- ceiling(exp(max(forestdata$uci, na.rm = T)))

  # c(bottom, left, top, right)
  par(mar = c(3, 18, 0, 0.5) + 0.2)

  gplots::plotCI(
    x = forestdata$logor, y = forestdata$order,
    li = forestdata$lci,
    ui = forestdata$uci,
    err = "x",
    cex = 0.7,
    xlim = c(
      log(minmy),
      log(maxmy)
    ),
    xlab = "",
    ylim = c(1, nrow(forestdata) - 1),
    axes = FALSE,
    ylab = "",
    main = NA,
    pch = 22,
    pt.bg = forestdata$cols,
    col = forestdata$cols,
    lwd = .9,
    gap = 0,
    sfrac = 0.001
  )

  abline(v = log(1), lty = 3, col = "grey")

  axis(1,
    cex.axis = cextext, at = log(c(minmy, 1, maxmy)),
    labels = c(minmy, 1, maxmy)
  )

  axis(2,
    at = forestdata$order,
    labels = forestdata$Variable,
    cex.axis = cextext, tick = FALSE, las = 2, line = 17, hadj = 0
  )

  axis(2,
    at = nrow(forestdata),
    labels = "Adjusted OR (95% CI)",
    cex.axis = cextext, tick = FALSE, las = 2, line = 2, hadj = 0.5, font = 2
  )
  axis(2,
    at = forestdata$order,
    labels = forestdata$orci,
    cex.axis = cextext, tick = FALSE, las = 2, line = 2, hadj = 0.5
  )

  axis(1,
    at = (log(maxmy) + log(minmy)) / 2, cex.axis = cextext,
    labels = "Adjusted OR (95% CI)", line = 1, tick = FALSE
  )
}
```

```{r ortab, dependson="ortabfunc", cache=cacheon}

predall <- predfunc(sglt2var = "sos_ddr_sglt2")

colnames(predall$predallprint) <- c("Variable", rep(c("OR (95% CI)", "p-value"), 2))

write.xlsx(predall$predallprint, paste0(
  "./output/tabs/Associations between SGLT2i use and characteristics_", Sys.Date(), ".xlsx"
), rowNames = FALSE, overwrite = TRUE)


default_kable(predall$predallprint,
  font_size = 6,
  caption = "Associations between SGLT2i use and characteristics",
  escape = T
) %>%
  add_header_above(c(" " = 1, "Crude" = 2, "Adjusted" = 2))
```

```{r orforestadj, cache=cacheon, dependson=c("ortabfunc", "ortab", "orforestfunc"), fig.width=5, fig.height=10, fig.cap="Adjusted associations between SGLT2i use and characteristics"}

predadj <- predall$predall %>%
  mutate(across(c("logor.y", "lci.y", "uci.y"), as.numeric)) %>%
  select(Variable, ends_with(".y"))

colnames(predadj) <- str_remove_all(colnames(predadj), ".y")

plotforest(forestdata = predadj)
```

\clearpage

```{r ortabdapa, dependson="ortabfunc", cache=cacheon}

predall <- predfunc(sglt2var = "sos_ddr_sglt2_Dapagliflozin")

colnames(predall$predallprint) <- c("Variable", rep(c("OR (95% CI)", "p-value"), 2))

write.xlsx(predall$predallprint, paste0(
  "./output/tabs/Associations between Dapagliflozin use and characteristics_", Sys.Date(), ".xlsx"
), rowNames = FALSE, overwrite = TRUE)


default_kable(predall$predallprint,
  font_size = 6,
  caption = "Associations between Dapagliflozin use and characteristics",
  escape = T
) %>%
  add_header_above(c(" " = 1, "Crude" = 2, "Adjusted" = 2))
```

```{r orforestadjdapa, cache=cacheon, dependson=c("ortabfunc", "ortabdapa", "orforestfunc"), fig.width=5, fig.height=10, fig.cap="Adjusted associations between Dapagliflozin use and characteristics"}

predadj <- predall$predall %>%
  mutate(across(c("logor.y", "lci.y", "uci.y"), as.numeric)) %>%
  select(Variable, ends_with(".y"))

colnames(predadj) <- str_remove_all(colnames(predadj), ".y")

plotforest(forestdata = predadj)
```

\clearpage

```{r ortabempa, dependson="ortabfunc", cache=cacheon}

predall <- predfunc(sglt2var = "sos_ddr_sglt2_Empagliflozin")

colnames(predall$predallprint) <- c("Variable", rep(c("OR (95% CI)", "p-value"), 2))

write.xlsx(predall$predallprint, paste0(
  "./output/tabs/Associations between Empagliflozin use and characteristics_", Sys.Date(), ".xlsx"
), rowNames = FALSE, overwrite = TRUE)


default_kable(predall$predallprint,
  font_size = 6,
  caption = "Associations between Empagliflozin use and characteristics",
  escape = T
) %>%
  add_header_above(c(" " = 1, "Crude" = 2, "Adjusted" = 2))
```

```{r orforestadjempa, cache=cacheon, dependson=c("ortabfunc", "ortabempa", "orforestfunc"), fig.width=5, fig.height=10, fig.cap="Adjusted associations between Empagliflozin use and characteristics"}

predadj <- predall$predall %>%
  mutate(across(c("logor.y", "lci.y", "uci.y"), as.numeric)) %>%
  select(Variable, ends_with(".y"))

colnames(predadj) <- str_remove_all(colnames(predadj), ".y")

plotforest(forestdata = predadj)
```





```{r sens-ortab, dependson="ortabfunc", cache=cacheon}

predall <- predfunc(sglt2var = "sos_ddr_sglt2", impdata = imprsdata_subset)

colnames(predall$predallprint) <- c("Variable", rep(c("OR (95% CI)", "p-value"), 2))

write.xlsx(predall$predallprint, paste0(
  "./output/tabs/sens_Associations between SGLT2i use and characteristics_", Sys.Date(), ".xlsx"
), rowNames = FALSE, overwrite = TRUE)


default_kable(predall$predallprint,
  font_size = 6,
  caption = "Associations between SGLT2i use and characteristics - excluding patients with Type I diabetes, eGFR < 20 and dialysis",
  escape = T
) %>%
  add_header_above(c(" " = 1, "Crude" = 2, "Adjusted" = 2))
```

```{r sens-orforestadj, cache=cacheon, dependson=c("ortabfunc", "sens-ortab", "orforestfunc"), fig.width=5, fig.height=10, fig.cap="Adjusted associations between SGLT2i use and characteristics - excluding patients with Type I diabetes, eGFR < 20 and dialysis"}

predadj <- predall$predall %>%
  mutate(across(c("logor.y", "lci.y", "uci.y"), as.numeric)) %>%
  select(Variable, ends_with(".y"))

colnames(predadj) <- str_remove_all(colnames(predadj), ".y")

plotforest(forestdata = predadj)
```

\clearpage

```{r sens-ortabdapa, dependson="ortabfunc", cache=cacheon}

predall <- predfunc(sglt2var = "sos_ddr_sglt2_Dapagliflozin", impdata = imprsdata_subset)

colnames(predall$predallprint) <- c("Variable", rep(c("OR (95% CI)", "p-value"), 2))

write.xlsx(predall$predallprint, paste0(
  "./output/tabs/sens_Associations between Dapagliflozin use and characteristics_", Sys.Date(), ".xlsx"
), rowNames = FALSE, overwrite = TRUE)


default_kable(predall$predallprint,
  font_size = 6,
  caption = "Associations between Dapagliflozin use and characteristics - excluding patients with Type I diabetes, eGFR < 20 and dialysis",
  escape = T
) %>%
  add_header_above(c(" " = 1, "Crude" = 2, "Adjusted" = 2))
```

```{r sens-orforestadjdapa, cache=cacheon, dependson=c("ortabfunc", "sens-ortabdapa", "orforestfunc"), fig.width=5, fig.height=10, fig.cap="Adjusted associations between Dapagliflozin use and characteristics - excluding patients with Type I diabetes, eGFR < 20 and dialysis"}

predadj <- predall$predall %>%
  mutate(across(c("logor.y", "lci.y", "uci.y"), as.numeric)) %>%
  select(Variable, ends_with(".y"))

colnames(predadj) <- str_remove_all(colnames(predadj), ".y")

plotforest(forestdata = predadj)
```

\clearpage

```{r sens-ortabempa, dependson="ortabfunc", cache=cacheon}

predall <- predfunc(sglt2var = "sos_ddr_sglt2_Empagliflozin", impdata = imprsdata_subset)

colnames(predall$predallprint) <- c("Variable", rep(c("OR (95% CI)", "p-value"), 2))

write.xlsx(predall$predallprint, paste0(
  "./output/tabs/sens_Associations between Empagliflozin use and characteristics_", Sys.Date(), ".xlsx"
), rowNames = FALSE, overwrite = TRUE)


default_kable(predall$predallprint,
  font_size = 6,
  caption = "Associations between Empagliflozin use and characteristics - excluding patients with Type I diabetes, eGFR < 20 and dialysis",
  escape = T
) %>%
  add_header_above(c(" " = 1, "Crude" = 2, "Adjusted" = 2))
```

```{r sens-orforestadjempa, cache=cacheon, dependson=c("ortabfunc", "sens-ortabempa", "orforestfunc"), fig.width=5, fig.height=10, fig.cap="Adjusted associations between Empagliflozin use and characteristics - excluding patients with Type I diabetes, eGFR < 20 and dialysis"}

predadj <- predall$predall %>%
  mutate(across(c("logor.y", "lci.y", "uci.y"), as.numeric)) %>%
  select(Variable, ends_with(".y"))

colnames(predadj) <- str_remove_all(colnames(predadj), ".y")

plotforest(forestdata = predadj)
```
