```{r overtimefunc, cache = cacheon}

overtimefunc <- function(overtimedata = overtime, filtergroups, groupnames, yearvar = "yearsemester", yearvarname = "Year:Semester") {
  cexmy <- 1.2
  # c(bottom, left, top, right) default c(5, 4, 4, 2) + 0.1.
  par(mar = c(6, 4, .5, 2.5) + 0.1)

  plot(overtimedata %>% filter(var == filtergroups[1]) %>% pull(count),
    overtimedata %>% filter(var == filtergroups[1]) %>% pull(percent),
    type = "b",
    pch = 19,
    lty = 1,
    col = global_cols[2],
    lwd = 2,
    # cex = 1.5,
    axes = FALSE,
    # xaxs = "i",
    # yaxs = "i",
    ylim = c(0, 100),
    # xlim = c(2012 - 0.5, 2018 + 0.5),
    ylab = "Percent",
    xlab = yearvarname,
    cex.lab = cexmy
  )
  matplot(overtimedata %>% filter(var == filtergroups[2]) %>% pull(count),
    overtimedata %>% filter(var == filtergroups[2]) %>% pull(percent),
    type = "b",
    pch = 19,
    lty = 1,
    col = "#cc9900",
    lwd = 2,
    add = T
  )
  if (length(filtergroups) == 3) {
    matplot(overtimedata %>% filter(var == filtergroups[3]) %>% pull(count),
      overtimedata %>% filter(var == filtergroups[3]) %>% pull(percent),
      type = "b",
      pch = 19,
      lty = 1,
      col = global_cols[6],
      lwd = 2,
      add = T
    )
  }
  legend(
    "topleft",
    bty = "n",
    groupnames,
    col = c(global_cols[2], "#cc9900", global_cols[6]),
    cex = cexmy, lwd = 2, lty = 1
  )
  axis(1, overtimedata %>% filter(var == filtergroups[1]) %>% pull(count),
    overtimedata %>% filter(var == filtergroups[1]) %>% pull(!!sym(yearvar)),
    cex.axis = cexmy, las = 1, gap.axis = 0.000001
  )

  axis(2, seq(0, 100, 10), las = 2, cex.axis = cexmy)
  # axis(2, seq(0, 40, 5), c(seq(0, 35, 5), 100), las = 2, cex.axis = cexmy)
  # plotrix::axis.break(2, 37.5, style = "slash")
}
```

```{r overtime, cache = cacheon, dependson="overtimefunc", fig.cap = "SGLT2i overtime - Alternative I", fig.show='hold', out.width="33%", fig.subcap=c('Overall and Substances', 'CKD', 'Diabetes (Type I excluded)', 'Previous HFH < 1 year', 'Location', 'Duration of HF', 'Sex'), fig.ncol=3}

overtimefunc(
  filtergroups = c("all", "dapa", "empa"),
  groupnames = c("SGLT2i", "Dapagliflozin", "Empagliflozin")
)
overtimefunc(
  filtergroups = c("ckd", "nockd"),
  groupnames = c("eGFR <60", "eGFR \u226560")
)
overtimefunc(
  filtergroups = c("type2", "notype2"),
  groupnames = c("Diabetes type II", "No diabetes")
)
overtimefunc(
  filtergroups = c("prevhfh", "noprevhfh"),
  groupnames = c("Previous HFH <1 year", "No previous HFH <1 year")
)
overtimefunc(
  filtergroups = c("inpat", "outpat"),
  groupnames = c("In-patient", "Out-patient")
)
overtimefunc(
  filtergroups = c("durhfmore", "durhfless"),
  groupnames = c("Duration of HF >6 months", "Duration of HF <6 months")
)
overtimefunc(
  filtergroups = c("male", "female"),
  groupnames = c("Male", "Female")
)
```

\clearpage

```{r overtimetab}
overtimetab <- overtime %>%
  mutate(percent = fn(percent, 1)) %>%
  select(var, yearsemester, den, num, percent)
default_kable(overtimetab,
  scale_down = FALSE,
  caption = "SGLT2i overtime (exact percent from Fig) - Alternative I", 
  longtable = T
)
```

```{r sens-overtime, cache = cacheon, dependson="overtimefunc", fig.cap = "SGLT2i overtime - Alternative I - excluding patients with Type I diabetes, eGFR < 20 and dialysis", fig.show='hold', out.width="33%", fig.subcap=c('Overall and Substances', 'CKD', 'Diabetes (Type I excluded)', 'Previous HFH < 1 year', 'Location', 'Duration of HF', 'Sex'), fig.ncol=3}

overtimefunc(
  overtimedata = overtime_subset, 
  filtergroups = c("all", "dapa", "empa"),
  groupnames = c("SGLT2i", "Dapagliflozin", "Empagliflozin")
)
overtimefunc(
  overtimedata = overtime_subset, 
  filtergroups = c("ckd", "nockd"),
  groupnames = c("eGFR <60", "eGFR \u226560")
)
overtimefunc(
  overtimedata = overtime_subset, 
  filtergroups = c("type2", "notype2"),
  groupnames = c("Diabetes type II", "No diabetes")
)
overtimefunc(
  overtimedata = overtime_subset, 
  filtergroups = c("prevhfh", "noprevhfh"),
  groupnames = c("Previous HFH <1 year", "No previous HFH <1 year")
)
overtimefunc(
  overtimedata = overtime_subset, 
  filtergroups = c("inpat", "outpat"),
  groupnames = c("In-patient", "Out-patient")
)
overtimefunc(
  overtimedata = overtime_subset, 
  filtergroups = c("durhfmore", "durhfless"),
  groupnames = c("Duration of HF >6 months", "Duration of HF <6 months")
)
overtimefunc(
  overtimedata = overtime_subset, 
  filtergroups = c("male", "female"),
  groupnames = c("Male", "Female")
)
```

\clearpage

```{r sens-overtimetab}
overtimetab <- overtime_subset %>%
  mutate(percent = fn(percent, 1)) %>%
  select(var, yearsemester, den, num, percent)
default_kable(overtimetab,
  scale_down = FALSE,
  caption = "SGLT2i overtime (exact percent from Fig) - Alternative I - excluding patients with Type I diabetes, eGFR < 20 and dialysis", 
  longtable = T
)
```

\clearpage

```{r overtimefunc2, cache = cacheon}

overtimefunccount <- function(sglt2var, rspop) {
  out <- rspop %>%
    group_by(shf_indexyearquarter) %>%
    count(!!sym(sglt2var)) %>%
    mutate(
      den = sum(n),
      percent = n / den * 100
    ) %>%
    ungroup() %>%
    rename(num = n) %>%
    filter(!!sym(sglt2var) == "Yes") %>%
    mutate(count = 1:n()) %>%
    select(-!!sym(sglt2var))
}

overtimeall <- overtimefunccount(sglt2var = "sos_ddr_sglt2", rspop = rsdata)
overtimedapa <- overtimefunccount(sglt2var = "sos_ddr_sglt2_Dapagliflozin", rspop = rsdata)
overtimeempa <- overtimefunccount(sglt2var = "sos_ddr_sglt2_Empagliflozin", rspop = rsdata)

overtimenockd <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_gfrckdepi_cat) & shf_gfrckdepi_cat == ">=60")
)
overtimeckd <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_gfrckdepi_cat) & shf_gfrckdepi_cat == "<60")
)
overtimenotype2 <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_sos_com_diabetestype) & shf_sos_com_diabetestype == "No")
)
overtimetype2 <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_sos_com_diabetestype) & shf_sos_com_diabetestype == "Type II")
)
overtimenoprevhfh <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_sos_prevhfh) & shf_sos_prevhfh == "No previous HFH <1 year")
)
overtimeprevhfh <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_sos_prevhfh) & shf_sos_prevhfh == "Previous HFH <1 year")
)
overtimeinpat <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_location) & shf_location == "In-patient")
)
overtimeoutpat <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_location) & shf_location == "Out-patient")
)
overtimedurhfmore <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_durationhf) & shf_durationhf == ">6mo")
)
overtimedurhfless <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_durationhf) & shf_durationhf == "<6mo")
)
overtimemale <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(shf_sex == "Male")
)
overtimefemale <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(shf_sex == "Female")
)

overtimeshf <- bind_rows(
  overtimeall %>% mutate(var = "all"),
  overtimedapa %>% mutate(var = "dapa"),
  overtimeempa %>% mutate(var = "empa"),
  overtimenockd %>% mutate(var = "nockd"),
  overtimeckd %>% mutate(var = "ckd"),
  overtimenotype2 %>% mutate(var = "notype2"),
  overtimetype2 %>% mutate(var = "type2"),
  overtimenoprevhfh %>% mutate(var = "noprevhfh"),
  overtimeprevhfh %>% mutate(var = "prevhfh"),
  overtimeinpat %>% mutate(var = "inpat"),
  overtimeoutpat %>% mutate(var = "outpat"),
  overtimedurhfmore %>% mutate(var = "durhfmore"),
  overtimedurhfless %>% mutate(var = "durhfless"),
  overtimemale %>% mutate(var = "male"),
  overtimefemale %>% mutate(var = "female")
)


overtimeall <- overtimefunccount(sglt2var = "sos_ddr_sglt2", rspop = rsdata %>% filter(subset))
overtimedapa <- overtimefunccount(sglt2var = "sos_ddr_sglt2_Dapagliflozin", rspop = rsdata %>% filter(subset))
overtimeempa <- overtimefunccount(sglt2var = "sos_ddr_sglt2_Empagliflozin", rspop = rsdata %>% filter(subset))

overtimenockd <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_gfrckdepi_cat) & shf_gfrckdepi_cat == ">=60" & subset)
)
overtimeckd <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_gfrckdepi_cat) & shf_gfrckdepi_cat == "<60" & subset)
)
overtimenotype2 <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_sos_com_diabetestype) & shf_sos_com_diabetestype == "No" & subset)
)
overtimetype2 <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_sos_com_diabetestype) & shf_sos_com_diabetestype == "Type II" & subset)
)
overtimenoprevhfh <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_sos_prevhfh) & shf_sos_prevhfh == "No previous HFH <1 year" & subset)
)
overtimeprevhfh <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_sos_prevhfh) & shf_sos_prevhfh == "Previous HFH <1 year" & subset)
)
overtimeinpat <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_location) & shf_location == "In-patient" & subset)
)
overtimeoutpat <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_location) & shf_location == "Out-patient" & subset)
)
overtimedurhfmore <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_durationhf) & shf_durationhf == ">6mo" & subset)
)
overtimedurhfless <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(!is.na(shf_durationhf) & shf_durationhf == "<6mo" & subset)
)
overtimemale <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(shf_sex == "Male" & subset)
)
overtimefemale <- overtimefunccount(
  sglt2var = "sos_ddr_sglt2",
  rspop = rsdata %>% filter(shf_sex == "Female" & subset)
)

overtimeshf_subset <- bind_rows(
  overtimeall %>% mutate(var = "all"),
  overtimedapa %>% mutate(var = "dapa"),
  overtimeempa %>% mutate(var = "empa"),
  overtimenockd %>% mutate(var = "nockd"),
  overtimeckd %>% mutate(var = "ckd"),
  overtimenotype2 %>% mutate(var = "notype2"),
  overtimetype2 %>% mutate(var = "type2"),
  overtimenoprevhfh %>% mutate(var = "noprevhfh"),
  overtimeprevhfh %>% mutate(var = "prevhfh"),
  overtimeinpat %>% mutate(var = "inpat"),
  overtimeoutpat %>% mutate(var = "outpat"),
  overtimedurhfmore %>% mutate(var = "durhfmore"),
  overtimedurhfless %>% mutate(var = "durhfless"),
  overtimemale %>% mutate(var = "male"),
  overtimefemale %>% mutate(var = "female")
)
```

```{r overtime2, cache = cacheon, dependson=c("overtimefunc", "overtimefunc2"), fig.cap = "SGLT2i overtime - Alternative II", fig.show='hold', out.width="33%", fig.subcap=c('Overall and Substances', 'CKD', 'Diabetes (Type I excluded)', 'Previous HFH < 1 year', 'Location', 'Duration of HF', 'Sex'), fig.ncol=3}

overtimefunc(
  overtimedata = overtimeshf,
  filtergroups = c("all", "dapa", "empa"),
  groupnames = c("SGLT2i", "Dapagliflozin", "Empagliflozin"),
  yearvar = "shf_indexyearquarter", yearvarname = "Year:Quarter"
)
overtimefunc(
  overtimedata = overtimeshf,
  filtergroups = c("ckd", "nockd"),
  groupnames = c("eGFR <60", "eGFR \u226560"),
  yearvar = "shf_indexyearquarter", yearvarname = "Year:Quarter"
)
overtimefunc(
  overtimedata = overtimeshf,
  filtergroups = c("type2", "notype2"),
  groupnames = c("Diabetes type II", "No diabetes"),
  yearvar = "shf_indexyearquarter", yearvarname = "Year:Quarter"
)
overtimefunc(
  overtimedata = overtimeshf,
  filtergroups = c("prevhfh", "noprevhfh"),
  groupnames = c("Previous HFH <1 year", "No previous HFH <1 year"),
  yearvar = "shf_indexyearquarter", yearvarname = "Year:Quarter"
)
overtimefunc(
  overtimedata = overtimeshf,
  filtergroups = c("inpat", "outpat"),
  groupnames = c("In-patient", "Out-patient"),
  yearvar = "shf_indexyearquarter", yearvarname = "Year:Quarter"
)
overtimefunc(
  overtimedata = overtimeshf,
  filtergroups = c("durhfmore", "durhfless"),
  groupnames = c("Duration of HF >6 months", "Duration of HF <6 months"),
  yearvar = "shf_indexyearquarter", yearvarname = "Year:Quarter"
)
overtimefunc(
  overtimedata = overtimeshf,
  filtergroups = c("male", "female"),
  groupnames = c("Male", "Female"),
  yearvar = "shf_indexyearquarter", yearvarname = "Year:Quarter"
)
```

\clearpage

```{r overtimetab2, cache = cacheon, dependson=c("overtimefunc2")}
overtimetab <- overtimeshf %>%
  mutate(percent = fn(percent, 1)) %>%
  select(var, shf_indexyearquarter, den, num, percent)
default_kable(overtimetab,
  scale_down = FALSE,
  caption = "SGLT2i overtime (exact percent from Fig) - Alternative II",
  longtable = T
)
```

```{r sens-overtime2, cache = cacheon, dependson=c("overtimefunc", "overtimefunc2"), fig.cap = "SGLT2i overtime - Alternative II - excluding patients with Type I diabetes, eGFR < 20 and dialysis", fig.show='hold', out.width="33%", fig.subcap=c('Overall and Substances', 'CKD', 'Diabetes (Type I excluded)', 'Previous HFH < 1 year', 'Location', 'Duration of HF', 'Sex'), fig.ncol=3}

overtimefunc(
  overtimedata = overtimeshf_subset,
  filtergroups = c("all", "dapa", "empa"),
  groupnames = c("SGLT2i", "Dapagliflozin", "Empagliflozin"),
  yearvar = "shf_indexyearquarter", yearvarname = "Year:Quarter"
)
overtimefunc(
  overtimedata = overtimeshf_subset,
  filtergroups = c("ckd", "nockd"),
  groupnames = c("eGFR <60", "eGFR \u226560"),
  yearvar = "shf_indexyearquarter", yearvarname = "Year:Quarter"
)
overtimefunc(
  overtimedata = overtimeshf_subset,
  filtergroups = c("type2", "notype2"),
  groupnames = c("Diabetes type II", "No diabetes"),
  yearvar = "shf_indexyearquarter", yearvarname = "Year:Quarter"
)
overtimefunc(
  overtimedata = overtimeshf_subset,
  filtergroups = c("prevhfh", "noprevhfh"),
  groupnames = c("Previous HFH <1 year", "No previous HFH <1 year"),
  yearvar = "shf_indexyearquarter", yearvarname = "Year:Quarter"
)
overtimefunc(
  overtimedata = overtimeshf_subset,
  filtergroups = c("inpat", "outpat"),
  groupnames = c("In-patient", "Out-patient"),
  yearvar = "shf_indexyearquarter", yearvarname = "Year:Quarter"
)
overtimefunc(
  overtimedata = overtimeshf_subset,
  filtergroups = c("durhfmore", "durhfless"),
  groupnames = c("Duration of HF >6 months", "Duration of HF <6 months"),
  yearvar = "shf_indexyearquarter", yearvarname = "Year:Quarter"
)
overtimefunc(
  overtimedata = overtimeshf_subset,
  filtergroups = c("male", "female"),
  groupnames = c("Male", "Female"),
  yearvar = "shf_indexyearquarter", yearvarname = "Year:Quarter"
)
```

\clearpage

```{r sens-overtimetab2, cache = cacheon, dependson=c("overtimefunc2")}
overtimetab <- overtimeshf_subset %>%
  mutate(percent = fn(percent, 1)) %>%
  select(var, shf_indexyearquarter, den, num, percent)
default_kable(overtimetab,
  scale_down = FALSE,
  caption = "SGLT2i overtime (exact percent from Fig) - Alternative II - excluding patients with Type I diabetes, eGFR < 20 and dialysis",
  longtable = T
)
```
